// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3AnbN6X7OMfDVWVTkBK-DV2IXiZHCwOk',
    appId: '1:335405609455:web:dd0efaa92ed376fc1f461a',
    messagingSenderId: '335405609455',
    projectId: 'interest-book-fierbase',
    authDomain: 'interest-book-fierbase.firebaseapp.com',
    storageBucket: 'interest-book-fierbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjfQJTaV6nQgmtEituGq_1cHjWj63Zhk',
    appId: '1:335405609455:android:34be825d38a8e76d1f461a',
    messagingSenderId: '335405609455',
    projectId: 'interest-book-fierbase',
    storageBucket: 'interest-book-fierbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfc2S2MP4DjRbYo-jHthigd8pd9C_hmQ0',
    appId: '1:335405609455:ios:b97bb0b8ff5fb04f1f461a',
    messagingSenderId: '335405609455',
    projectId: 'interest-book-fierbase',
    storageBucket: 'interest-book-fierbase.firebasestorage.app',
    iosBundleId: 'com.example.interestBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfc2S2MP4DjRbYo-jHthigd8pd9C_hmQ0',
    appId: '1:335405609455:ios:b97bb0b8ff5fb04f1f461a',
    messagingSenderId: '335405609455',
    projectId: 'interest-book-fierbase',
    storageBucket: 'interest-book-fierbase.firebasestorage.app',
    iosBundleId: 'com.example.interestBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3AnbN6X7OMfDVWVTkBK-DV2IXiZHCwOk',
    appId: '1:335405609455:web:c868c50cb62d0a1e1f461a',
    messagingSenderId: '335405609455',
    projectId: 'interest-book-fierbase',
    authDomain: 'interest-book-fierbase.firebaseapp.com',
    storageBucket: 'interest-book-fierbase.firebasestorage.app',
  );
}
